# Site settings
title: "Sneh Patel - Resume"
# description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sneh Patel"
resume_title:                   "Data Scientist | Machine Learning Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "snehpatel@0308gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91-8320672038"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

# resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
# display_header_contact_info:    "false"

resume_header_intro: "<p>A results-oriented Computer Engineering undergraduate with expertise in data science, machine learning, and AI. Skilled in developing end-to-end solutions using Python, TensorFlow, and PyTorch. Passionate about leveraging advanced technologies to drive innovation, solve complex challenges, and contribute to impactful AI-driven solutions. Seeking opportunities to apply technical expertise and analytical skills in real-world projects to further enhance my career in AI and data science.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/snehpatel38"
  resume_twitter_url:           "https://x.com/SnehPatel03"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/snehpatel38"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@snehpatel0308"
resume_print_social_links:      true

# Design settings
resume_theme:                   default